version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y lsb-release curl
            curl -sSL https://get.docker.com/ > docker.sh && chmod +x docker.sh && ./docker.sh
      - run:
          name: Install gcloud SDK
          command: |
            export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
            apt-get update -y && apt-get install -y google-cloud-sdk kubectl
      - run:
          name: Initialise & authenticate gcloud SDK
          command: |
            echo "${GCP_KEY_FILE}" | base64 --decode >> /tmp/gcp_key.json
            gcloud auth activate-service-account --key-file /tmp/gcp_key.json
            gcloud config set project ${GCP_ACCOUNT_ID}
            gcloud config set compute/zone ${GCP_ZONE}
            gcloud container clusters get-credentials ${GCP_CLUSTER_DEVELOPMENT}
      - run:
          name: Build & Deploy Services
          command: |
            docker build -t blockexplorer .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            export DOCKER_IMAGE=jakebunce/blockexplorer:$CIRCLE_SHA1
            docker tag blockexplorer $DOCKER_IMAGE
            docker push jakebunce/blockexplorer:$CIRCLE_SHA1
            kubectl set image deployment blockexplorer blockexplorer=$DOCKER_IMAGE

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
